<?php

declare (strict_types=1);
namespace ApiClients\Client\GitHub\Schema\GistSimple;

use ApiClients\Client\GitHub\Error as ErrorSchemas;
use ApiClients\Client\GitHub\Hydrator;
use ApiClients\Client\GitHub\Operation;
use ApiClients\Client\GitHub\Schema;
use ApiClients\Client\GitHub\WebHook;
final readonly class Forks
{
    public const SCHEMA_JSON = '{"type":"object","properties":{"id":{"type":"string"},"url":{"type":"string","format":"uri"},"user":{"title":"Public User","required":["avatar_url","events_url","followers_url","following_url","gists_url","gravatar_id","html_url","id","node_id","login","organizations_url","received_events_url","repos_url","site_admin","starred_url","subscriptions_url","type","url","bio","blog","company","email","followers","following","hireable","location","name","public_gists","public_repos","created_at","updated_at"],"type":"object","properties":{"login":{"type":"string"},"id":{"type":"integer"},"node_id":{"type":"string"},"avatar_url":{"type":"string","format":"uri"},"gravatar_id":{"type":["string","null"]},"url":{"type":"string","format":"uri"},"html_url":{"type":"string","format":"uri"},"followers_url":{"type":"string","format":"uri"},"following_url":{"type":"string"},"gists_url":{"type":"string"},"starred_url":{"type":"string"},"subscriptions_url":{"type":"string","format":"uri"},"organizations_url":{"type":"string","format":"uri"},"repos_url":{"type":"string","format":"uri"},"events_url":{"type":"string"},"received_events_url":{"type":"string","format":"uri"},"type":{"type":"string"},"site_admin":{"type":"boolean"},"name":{"type":["string","null"]},"company":{"type":["string","null"]},"blog":{"type":["string","null"]},"location":{"type":["string","null"]},"email":{"type":["string","null"],"format":"email"},"hireable":{"type":["boolean","null"]},"bio":{"type":["string","null"]},"twitter_username":{"type":["string","null"]},"public_repos":{"type":"integer"},"public_gists":{"type":"integer"},"followers":{"type":"integer"},"following":{"type":"integer"},"created_at":{"type":"string","format":"date-time"},"updated_at":{"type":"string","format":"date-time"},"plan":{"required":["collaborators","name","space","private_repos"],"type":"object","properties":{"collaborators":{"type":"integer"},"name":{"type":"string"},"space":{"type":"integer"},"private_repos":{"type":"integer"}}},"suspended_at":{"type":["string","null"],"format":"date-time"},"private_gists":{"type":"integer","examples":[1]},"total_private_repos":{"type":"integer","examples":[2]},"owned_private_repos":{"type":"integer","examples":[2]},"disk_usage":{"type":"integer","examples":[1]},"collaborators":{"type":"integer","examples":[3]}},"description":"Public User","additionalProperties":false},"created_at":{"type":"string","format":"date-time"},"updated_at":{"type":"string","format":"date-time"}}}';
    public const SCHEMA_TITLE = '';
    public const SCHEMA_DESCRIPTION = '';
    public const SCHEMA_EXAMPLE_DATA = '{"id":"generated_id_null","url":"https:\\/\\/example.com\\/","user":{"login":"generated_login_null","id":13,"nodeId":"generated_node_id_null","avatarUrl":"https:\\/\\/example.com\\/","gravatarId":"generated_gravatar_id_null","url":"https:\\/\\/example.com\\/","htmlUrl":"https:\\/\\/example.com\\/","followersUrl":"https:\\/\\/example.com\\/","followingUrl":"generated_following_url_null","gistsUrl":"generated_gists_url_null","starredUrl":"generated_starred_url_null","subscriptionsUrl":"https:\\/\\/example.com\\/","organizationsUrl":"https:\\/\\/example.com\\/","reposUrl":"https:\\/\\/example.com\\/","eventsUrl":"generated_events_url_null","receivedEventsUrl":"https:\\/\\/example.com\\/","type":"generated_type_null","siteAdmin":false,"name":"generated_name_null","company":"generated_company_null","blog":"generated_blog_null","location":"generated_location_null","email":"generated_email_email","hireable":false,"bio":"generated_bio_null","twitterUsername":"generated_twitter_username_null","publicRepos":13,"publicGists":13,"followers":13,"following":13,"createdAt":"1970-01-01T00:00:00+00:00","updatedAt":"1970-01-01T00:00:00+00:00","plan":{"collaborators":13,"name":"generated_name_null","space":13,"privateRepos":13},"suspendedAt":"1970-01-01T00:00:00+00:00","privateGists":1,"totalPrivateRepos":2,"ownedPrivateRepos":2,"diskUsage":1,"collaborators":3},"createdAt":"1970-01-01T00:00:00+00:00","updatedAt":"1970-01-01T00:00:00+00:00"}';
    /**
     * user: Public User
     */
    public function __construct(public ?string $id, public ?string $url, public ?Schema\PublicUser $user, #[\EventSauce\ObjectHydrator\MapFrom('created_at')] public ?string $createdAt, #[\EventSauce\ObjectHydrator\MapFrom('updated_at')] public ?string $updatedAt)
    {
    }
}
