<?php

declare(strict_types=1);

namespace ApiClients\Client\Github\OpenAPI\ApiGitHubCom\Operation\EnterpriseAdmin;

use Psr\Http\Message\RequestInterface;
use RingCentral\Psr7\Request;

use function str_replace;

final class GetProvisioningInformationForEnterpriseGroup
{
    private const OPERATION_ID = 'enterprise-admin/get-provisioning-information-for-enterprise-group';
    /**The slug version of the enterprise name. You can also substitute this value with the enterprise id.**/
    public string $enterprise;
    /**Identifier generated by the GitHub SCIM endpoint.**/
    public string $scim_group_id;
    /**Attributes to exclude.**/
    public string $excludedAttributes;

    public function operationId(): string
    {
        return self::OPERATION_ID;
    }

    function __construct($enterprise, $scim_group_id, $excludedAttributes)
    {
        $this->enterprise         = $enterprise;
        $this->scim_group_id      = $scim_group_id;
        $this->excludedAttributes = $excludedAttributes;
    }

    function createRequest(): RequestInterface
    {
        return new Request('get', str_replace(['{enterprise}', '{scim_group_id}', '{excludedAttributes}'], [$this->enterprise, $this->scim_group_id, $this->excludedAttributes], '/scim/v2/enterprises/{enterprise}/Groups/{scim_group_id}?excludedAttributes={excludedAttributes}'));
    }

    function validateResponse(): void
    {
    }
}
