<?php

namespace ApiClients\Client\Github\OpenAPI\GitHubAE\Operation\EnterpriseAdmin;

final class GetProvisioningInformationForEnterpriseGroup
{
    private const OPERATION_ID = 'enterprise-admin/get-provisioning-information-for-enterprise-group';
    /**The slug version of the enterprise name. You can also substitute this value with the enterprise id.**/
    public string $enterprise;
    /**Identifier generated by the GitHub SCIM endpoint.**/
    public string $scim_group_id;
    /**Attributes to exclude.**/
    public string $excludedAttributes;
    public function operationId() : string
    {
        return self::OPERATION_ID;
    }
    function __construct($enterprise, $scim_group_id, $excludedAttributes)
    {
        $this->enterprise = $enterprise;
        $this->scim_group_id = $scim_group_id;
        $this->excludedAttributes = $excludedAttributes;
    }
    function createRequest() : \Psr\Http\Message\RequestInterface
    {
        return new \RingCentral\Psr7\Request('get', \str_replace(array('{enterprise}', '{scim_group_id}', '{excludedAttributes}'), array($this->enterprise, $this->scim_group_id, $this->excludedAttributes), '/scim/v2/enterprises/{enterprise}/Groups/{scim_group_id}?excludedAttributes={excludedAttributes}'));
    }
    function validateResponse()
    {
    }
}
