<?php

declare (strict_types=1);
namespace ApiClients\Client\GitHub\Schema\PagesHealthCheck;

use ApiClients\Client\GitHub\Error as ErrorSchemas;
use ApiClients\Client\GitHub\Hydrator;
use ApiClients\Client\GitHub\Operation;
use ApiClients\Client\GitHub\Schema;
use ApiClients\Client\GitHub\WebHook;
final readonly class Domain
{
    public const SCHEMA_JSON = '{"type":"object","properties":{"host":{"type":"string"},"uri":{"type":"string"},"nameservers":{"type":"string"},"dns_resolves":{"type":"boolean"},"is_proxied":{"type":["boolean","null"]},"is_cloudflare_ip":{"type":["boolean","null"]},"is_fastly_ip":{"type":["boolean","null"]},"is_old_ip_address":{"type":["boolean","null"]},"is_a_record":{"type":["boolean","null"]},"has_cname_record":{"type":["boolean","null"]},"has_mx_records_present":{"type":["boolean","null"]},"is_valid_domain":{"type":"boolean"},"is_apex_domain":{"type":"boolean"},"should_be_a_record":{"type":["boolean","null"]},"is_cname_to_github_user_domain":{"type":["boolean","null"]},"is_cname_to_pages_dot_github_dot_com":{"type":["boolean","null"]},"is_cname_to_fastly":{"type":["boolean","null"]},"is_pointed_to_github_pages_ip":{"type":["boolean","null"]},"is_non_github_pages_ip_present":{"type":["boolean","null"]},"is_pages_domain":{"type":"boolean"},"is_served_by_pages":{"type":["boolean","null"]},"is_valid":{"type":"boolean"},"reason":{"type":["string","null"]},"responds_to_https":{"type":"boolean"},"enforces_https":{"type":"boolean"},"https_error":{"type":["string","null"]},"is_https_eligible":{"type":["boolean","null"]},"caa_error":{"type":["string","null"]}}}';
    public const SCHEMA_TITLE = '';
    public const SCHEMA_DESCRIPTION = '';
    public const SCHEMA_EXAMPLE_DATA = '{"host":"generated_host_null","uri":"generated_uri_null","nameservers":"generated_nameservers_null","dnsResolves":false,"isProxied":false,"isCloudflareIp":false,"isFastlyIp":false,"isOldIpAddress":false,"isARecord":false,"hasCnameRecord":false,"hasMxRecordsPresent":false,"isValidDomain":false,"isApexDomain":false,"shouldBeARecord":false,"isCnameToGithubUserDomain":false,"isCnameToPagesDotGithubDotCom":false,"isCnameToFastly":false,"isPointedToGithubPagesIp":false,"isNonGithubPagesIpPresent":false,"isPagesDomain":false,"isServedByPages":false,"isValid":false,"reason":"generated_reason_null","respondsToHttps":false,"enforcesHttps":false,"httpsError":"generated_https_error_null","isHttpsEligible":false,"caaError":"generated_caa_error_null"}';
    public function __construct(public ?string $host, public ?string $uri, public ?string $nameservers, #[\EventSauce\ObjectHydrator\MapFrom('dns_resolves')] public ?bool $dnsResolves, #[\EventSauce\ObjectHydrator\MapFrom('is_proxied')] public ?bool $isProxied, #[\EventSauce\ObjectHydrator\MapFrom('is_cloudflare_ip')] public ?bool $isCloudflareIp, #[\EventSauce\ObjectHydrator\MapFrom('is_fastly_ip')] public ?bool $isFastlyIp, #[\EventSauce\ObjectHydrator\MapFrom('is_old_ip_address')] public ?bool $isOldIpAddress, #[\EventSauce\ObjectHydrator\MapFrom('is_a_record')] public ?bool $isARecord, #[\EventSauce\ObjectHydrator\MapFrom('has_cname_record')] public ?bool $hasCnameRecord, #[\EventSauce\ObjectHydrator\MapFrom('has_mx_records_present')] public ?bool $hasMxRecordsPresent, #[\EventSauce\ObjectHydrator\MapFrom('is_valid_domain')] public ?bool $isValidDomain, #[\EventSauce\ObjectHydrator\MapFrom('is_apex_domain')] public ?bool $isApexDomain, #[\EventSauce\ObjectHydrator\MapFrom('should_be_a_record')] public ?bool $shouldBeARecord, #[\EventSauce\ObjectHydrator\MapFrom('is_cname_to_github_user_domain')] public ?bool $isCnameToGithubUserDomain, #[\EventSauce\ObjectHydrator\MapFrom('is_cname_to_pages_dot_github_dot_com')] public ?bool $isCnameToPagesDotGithubDotCom, #[\EventSauce\ObjectHydrator\MapFrom('is_cname_to_fastly')] public ?bool $isCnameToFastly, #[\EventSauce\ObjectHydrator\MapFrom('is_pointed_to_github_pages_ip')] public ?bool $isPointedToGithubPagesIp, #[\EventSauce\ObjectHydrator\MapFrom('is_non_github_pages_ip_present')] public ?bool $isNonGithubPagesIpPresent, #[\EventSauce\ObjectHydrator\MapFrom('is_pages_domain')] public ?bool $isPagesDomain, #[\EventSauce\ObjectHydrator\MapFrom('is_served_by_pages')] public ?bool $isServedByPages, #[\EventSauce\ObjectHydrator\MapFrom('is_valid')] public ?bool $isValid, public ?string $reason, #[\EventSauce\ObjectHydrator\MapFrom('responds_to_https')] public ?bool $respondsToHttps, #[\EventSauce\ObjectHydrator\MapFrom('enforces_https')] public ?bool $enforcesHttps, #[\EventSauce\ObjectHydrator\MapFrom('https_error')] public ?string $httpsError, #[\EventSauce\ObjectHydrator\MapFrom('is_https_eligible')] public ?bool $isHttpsEligible, #[\EventSauce\ObjectHydrator\MapFrom('caa_error')] public ?string $caaError)
    {
    }
}
