<?php

declare(strict_types=1);

namespace ApiClients\Client\GitHub\Schema\PagesHealthCheck;

use EventSauce\ObjectHydrator\MapFrom;

final readonly class Domain
{
    public const SCHEMA_JSON         = '{"type":"object","properties":{"host":{"type":"string"},"uri":{"type":"string"},"nameservers":{"type":"string"},"dns_resolves":{"type":"boolean"},"is_proxied":{"type":["boolean","null"]},"is_cloudflare_ip":{"type":["boolean","null"]},"is_fastly_ip":{"type":["boolean","null"]},"is_old_ip_address":{"type":["boolean","null"]},"is_a_record":{"type":["boolean","null"]},"has_cname_record":{"type":["boolean","null"]},"has_mx_records_present":{"type":["boolean","null"]},"is_valid_domain":{"type":"boolean"},"is_apex_domain":{"type":"boolean"},"should_be_a_record":{"type":["boolean","null"]},"is_cname_to_github_user_domain":{"type":["boolean","null"]},"is_cname_to_pages_dot_github_dot_com":{"type":["boolean","null"]},"is_cname_to_fastly":{"type":["boolean","null"]},"is_pointed_to_github_pages_ip":{"type":["boolean","null"]},"is_non_github_pages_ip_present":{"type":["boolean","null"]},"is_pages_domain":{"type":"boolean"},"is_served_by_pages":{"type":["boolean","null"]},"is_valid":{"type":"boolean"},"reason":{"type":["string","null"]},"responds_to_https":{"type":"boolean"},"enforces_https":{"type":"boolean"},"https_error":{"type":["string","null"]},"is_https_eligible":{"type":["boolean","null"]},"caa_error":{"type":["string","null"]}}}';
    public const SCHEMA_TITLE        = '';
    public const SCHEMA_DESCRIPTION  = '';
    public const SCHEMA_EXAMPLE_DATA = '{"host":"generated_host_null","uri":"generated_uri_null","nameservers":"generated_nameservers_null","dns_resolves":false,"is_proxied":false,"is_cloudflare_ip":false,"is_fastly_ip":false,"is_old_ip_address":false,"is_a_record":false,"has_cname_record":false,"has_mx_records_present":false,"is_valid_domain":false,"is_apex_domain":false,"should_be_a_record":false,"is_cname_to_github_user_domain":false,"is_cname_to_pages_dot_github_dot_com":false,"is_cname_to_fastly":false,"is_pointed_to_github_pages_ip":false,"is_non_github_pages_ip_present":false,"is_pages_domain":false,"is_served_by_pages":false,"is_valid":false,"reason":"generated_reason_null","responds_to_https":false,"enforces_https":false,"https_error":"generated_https_error_null","is_https_eligible":false,"caa_error":"generated_caa_error_null"}';

    public function __construct(public ?string $host, public ?string $uri, public ?string $nameservers, #[MapFrom('dns_resolves')] public ?bool $dnsResolves, #[MapFrom('is_proxied')] public ?bool $isProxied, #[MapFrom('is_cloudflare_ip')] public ?bool $isCloudflareIp, #[MapFrom('is_fastly_ip')] public ?bool $isFastlyIp, #[MapFrom('is_old_ip_address')] public ?bool $isOldIpAddress, #[MapFrom('is_a_record')] public ?bool $isARecord, #[MapFrom('has_cname_record')] public ?bool $hasCnameRecord, #[MapFrom('has_mx_records_present')] public ?bool $hasMxRecordsPresent, #[MapFrom('is_valid_domain')] public ?bool $isValidDomain, #[MapFrom('is_apex_domain')] public ?bool $isApexDomain, #[MapFrom('should_be_a_record')] public ?bool $shouldBeARecord, #[MapFrom('is_cname_to_github_user_domain')] public ?bool $isCnameToGithubUserDomain, #[MapFrom('is_cname_to_pages_dot_github_dot_com')] public ?bool $isCnameToPagesDotGithubDotCom, #[MapFrom('is_cname_to_fastly')] public ?bool $isCnameToFastly, #[MapFrom('is_pointed_to_github_pages_ip')] public ?bool $isPointedToGithubPagesIp, #[MapFrom('is_non_github_pages_ip_present')] public ?bool $isNonGithubPagesIpPresent, #[MapFrom('is_pages_domain')] public ?bool $isPagesDomain, #[MapFrom('is_served_by_pages')] public ?bool $isServedByPages, #[MapFrom('is_valid')] public ?bool $isValid, public ?string $reason, #[MapFrom('responds_to_https')] public ?bool $respondsToHttps, #[MapFrom('enforces_https')] public ?bool $enforcesHttps, #[MapFrom('https_error')] public ?string $httpsError, #[MapFrom('is_https_eligible')] public ?bool $isHttpsEligible, #[MapFrom('caa_error')] public ?string $caaError)
    {
    }
}
