<?php

declare(strict_types=1);

namespace ApiClients\Client\GitHub\Schema\WebhookPackagePublished\Package\PackageVersion;

use EventSauce\ObjectHydrator\MapFrom;

final readonly class NpmMetadata
{
    public const SCHEMA_JSON         = '{"type":["object","null"],"properties":{"name":{"type":"string"},"version":{"type":"string"},"npm_user":{"type":"string"},"author":{"type":["object","null"]},"bugs":{"type":["object","null"]},"dependencies":{"type":"object"},"dev_dependencies":{"type":"object"},"peer_dependencies":{"type":"object"},"optional_dependencies":{"type":"object"},"description":{"type":"string"},"dist":{"type":["object","null"]},"git_head":{"type":"string"},"homepage":{"type":"string"},"license":{"type":"string"},"main":{"type":"string"},"repository":{"type":["object","null"]},"scripts":{"type":"object"},"id":{"type":"string"},"node_version":{"type":"string"},"npm_version":{"type":"string"},"has_shrinkwrap":{"type":"boolean"},"maintainers":{"type":"array","items":{"type":"object"}},"contributors":{"type":"array","items":{"type":"object"}},"engines":{"type":"object"},"keywords":{"type":"array","items":{"type":"string"}},"files":{"type":"array","items":{"type":"string"}},"bin":{"type":"object"},"man":{"type":"object"},"directories":{"type":["object","null"]},"os":{"type":"array","items":{"type":"string"}},"cpu":{"type":"array","items":{"type":"string"}},"readme":{"type":"string"},"installation_command":{"type":"string"},"release_id":{"type":"integer"},"commit_oid":{"type":"string"},"published_via_actions":{"type":"boolean"},"deleted_by_id":{"type":"integer"}}}';
    public const SCHEMA_TITLE        = '';
    public const SCHEMA_DESCRIPTION  = '';
    public const SCHEMA_EXAMPLE_DATA = '{"name":"generated","version":"generated","npm_user":"generated","author":"generated","bugs":"generated","dependencies":"generated","dev_dependencies":"generated","peer_dependencies":"generated","optional_dependencies":"generated","description":"generated","dist":"generated","git_head":"generated","homepage":"generated","license":"generated","main":"generated","repository":"generated","scripts":"generated","id":"generated","node_version":"generated","npm_version":"generated","has_shrinkwrap":false,"maintainers":[[],[]],"contributors":[[],[]],"engines":"generated","keywords":["generated","generated"],"files":["generated","generated"],"bin":"generated","man":"generated","directories":"generated","os":["generated","generated"],"cpu":["generated","generated"],"readme":"generated","installation_command":"generated","release_id":10,"commit_oid":"generated","published_via_actions":false,"deleted_by_id":13}';

    public function __construct(public ?string $name, public ?string $version, #[MapFrom('npm_user')] public ?string $npmUser, public string $author, public string $bugs, public string $dependencies, #[MapFrom('dev_dependencies')] public string $devDependencies, #[MapFrom('peer_dependencies')] public string $peerDependencies, #[MapFrom('optional_dependencies')] public string $optionalDependencies, public ?string $description, public string $dist, #[MapFrom('git_head')] public ?string $gitHead, public ?string $homepage, public ?string $license, public ?string $main, public string $repository, public string $scripts, public ?string $id, #[MapFrom('node_version')] public ?string $nodeVersion, #[MapFrom('npm_version')] public ?string $npmVersion, #[MapFrom('has_shrinkwrap')] public ?bool $hasShrinkwrap, public ?array $maintainers, public ?array $contributors, public string $engines, public ?array $keywords, public ?array $files, public string $bin, public string $man, public string $directories, public ?array $os, public ?array $cpu, public ?string $readme, #[MapFrom('installation_command')] public ?string $installationCommand, #[MapFrom('release_id')] public ?int $releaseId, #[MapFrom('commit_oid')] public ?string $commitOid, #[MapFrom('published_via_actions')] public ?bool $publishedViaActions, #[MapFrom('deleted_by_id')] public ?int $deletedById)
    {
    }
}
