<?php

declare (strict_types=1);
namespace ApiClients\Client\GitHub\Schema;

use ApiClients\Client\GitHub\Error as ErrorSchemas;
use ApiClients\Client\GitHub\Hydrator;
use ApiClients\Client\GitHub\Operation;
use ApiClients\Client\GitHub\Schema;
use ApiClients\Client\GitHub\WebHook;
final readonly class PagesHealthCheck
{
    public const SCHEMA_JSON = '{"title":"Pages Health Check Status","type":"object","properties":{"domain":{"type":"object","properties":{"host":{"type":"string"},"uri":{"type":"string"},"nameservers":{"type":"string"},"dns_resolves":{"type":"boolean"},"is_proxied":{"type":["boolean","null"]},"is_cloudflare_ip":{"type":["boolean","null"]},"is_fastly_ip":{"type":["boolean","null"]},"is_old_ip_address":{"type":["boolean","null"]},"is_a_record":{"type":["boolean","null"]},"has_cname_record":{"type":["boolean","null"]},"has_mx_records_present":{"type":["boolean","null"]},"is_valid_domain":{"type":"boolean"},"is_apex_domain":{"type":"boolean"},"should_be_a_record":{"type":["boolean","null"]},"is_cname_to_github_user_domain":{"type":["boolean","null"]},"is_cname_to_pages_dot_github_dot_com":{"type":["boolean","null"]},"is_cname_to_fastly":{"type":["boolean","null"]},"is_pointed_to_github_pages_ip":{"type":["boolean","null"]},"is_non_github_pages_ip_present":{"type":["boolean","null"]},"is_pages_domain":{"type":"boolean"},"is_served_by_pages":{"type":["boolean","null"]},"is_valid":{"type":"boolean"},"reason":{"type":["string","null"]},"responds_to_https":{"type":"boolean"},"enforces_https":{"type":"boolean"},"https_error":{"type":["string","null"]},"is_https_eligible":{"type":["boolean","null"]},"caa_error":{"type":["string","null"]}}},"alt_domain":{"type":["object","null"],"properties":{"host":{"type":"string"},"uri":{"type":"string"},"nameservers":{"type":"string"},"dns_resolves":{"type":"boolean"},"is_proxied":{"type":["boolean","null"]},"is_cloudflare_ip":{"type":["boolean","null"]},"is_fastly_ip":{"type":["boolean","null"]},"is_old_ip_address":{"type":["boolean","null"]},"is_a_record":{"type":["boolean","null"]},"has_cname_record":{"type":["boolean","null"]},"has_mx_records_present":{"type":["boolean","null"]},"is_valid_domain":{"type":"boolean"},"is_apex_domain":{"type":"boolean"},"should_be_a_record":{"type":["boolean","null"]},"is_cname_to_github_user_domain":{"type":["boolean","null"]},"is_cname_to_pages_dot_github_dot_com":{"type":["boolean","null"]},"is_cname_to_fastly":{"type":["boolean","null"]},"is_pointed_to_github_pages_ip":{"type":["boolean","null"]},"is_non_github_pages_ip_present":{"type":["boolean","null"]},"is_pages_domain":{"type":"boolean"},"is_served_by_pages":{"type":["boolean","null"]},"is_valid":{"type":"boolean"},"reason":{"type":["string","null"]},"responds_to_https":{"type":"boolean"},"enforces_https":{"type":"boolean"},"https_error":{"type":["string","null"]},"is_https_eligible":{"type":["boolean","null"]},"caa_error":{"type":["string","null"]}}}},"description":"Pages Health Check Status"}';
    public const SCHEMA_TITLE = 'Pages Health Check Status';
    public const SCHEMA_DESCRIPTION = 'Pages Health Check Status';
    public const SCHEMA_EXAMPLE_DATA = '{"domain":{"host":"generated_host_null","uri":"generated_uri_null","nameservers":"generated_nameservers_null","dnsResolves":false,"isProxied":false,"isCloudflareIp":false,"isFastlyIp":false,"isOldIpAddress":false,"isARecord":false,"hasCnameRecord":false,"hasMxRecordsPresent":false,"isValidDomain":false,"isApexDomain":false,"shouldBeARecord":false,"isCnameToGithubUserDomain":false,"isCnameToPagesDotGithubDotCom":false,"isCnameToFastly":false,"isPointedToGithubPagesIp":false,"isNonGithubPagesIpPresent":false,"isPagesDomain":false,"isServedByPages":false,"isValid":false,"reason":"generated_reason_null","respondsToHttps":false,"enforcesHttps":false,"httpsError":"generated_https_error_null","isHttpsEligible":false,"caaError":"generated_caa_error_null"},"altDomain":{"host":"generated_host_null","uri":"generated_uri_null","nameservers":"generated_nameservers_null","dnsResolves":false,"isProxied":false,"isCloudflareIp":false,"isFastlyIp":false,"isOldIpAddress":false,"isARecord":false,"hasCnameRecord":false,"hasMxRecordsPresent":false,"isValidDomain":false,"isApexDomain":false,"shouldBeARecord":false,"isCnameToGithubUserDomain":false,"isCnameToPagesDotGithubDotCom":false,"isCnameToFastly":false,"isPointedToGithubPagesIp":false,"isNonGithubPagesIpPresent":false,"isPagesDomain":false,"isServedByPages":false,"isValid":false,"reason":"generated_reason_null","respondsToHttps":false,"enforcesHttps":false,"httpsError":"generated_https_error_null","isHttpsEligible":false,"caaError":"generated_caa_error_null"}}';
    public function __construct(public ?Schema\PagesHealthCheck\Domain $domain, #[\EventSauce\ObjectHydrator\MapFrom('alt_domain')] public ?Schema\PagesHealthCheck\AltDomain $altDomain)
    {
    }
}
